Authentication on the backend
rodzers-usackis/elision-internship-backend pull request #6
Opened 2023-04-25 15:24 UTC by Dominik-Mika

2023-04-27 07:05 UTC, Gschrooyen requested changes
add javadoc everywhere

2023-04-27 07:05 UTC, Gschrooyen commented on src/main/java/eu/elision/pricing/domain/User.java
> +@Getter
use @Data

2023-04-27 07:05 UTC, Gschrooyen commented on src/main/java/eu/elision/pricing/security/SecurityConfig.java
> +        DaoAuthenticationProvider daoAuthenticationProvider = new DaoAuthenticationProvider();
autowire this

2023-05-05 08:37 UTC, rodzers-usackis approved these changes

2023-05-05 08:43 UTC, rodzers-usackis approved these changes

2023-05-05 08:44 UTC, Dominik-Mika commented
Requested changes implemented.

2023-05-05 08:46 UTC, merged